//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementSystemMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassAllocateTB
    {
        public int Id { get; set; }
        public int DepartmentId { get; set; }
        public int RoomId { get; set; }
        public int CourseId { get; set; }
        public int DayId { get; set; }
        public System.DateTime FromTime { get; set; }
        public System.DateTime ToTime { get; set; }
        public int Action { get; set; }
    
        public virtual CourseTB CourseTB { get; set; }
        public virtual RoomNoTB RoomNoTB { get; set; }
    }
}
