//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementSystemMVCApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmSEntities : DbContext
    {
        public SmSEntities()
            : base("name=SmSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminTB> AdminTBs { get; set; }
        public virtual DbSet<RoleTB> RoleTBs { get; set; }
        public virtual DbSet<StudentTB> StudentTBs { get; set; }
        public virtual DbSet<TeacherTB> TeacherTBs { get; set; }
        public virtual DbSet<CodeingClubTB> CodeingClubTBs { get; set; }
        public virtual DbSet<CodingClubAdvTB> CodingClubAdvTBs { get; set; }
        public virtual DbSet<NetClubAdvTB> NetClubAdvTBs { get; set; }
        public virtual DbSet<NetworkingClubTB> NetworkingClubTBs { get; set; }
        public virtual DbSet<ClassAllocateTB> ClassAllocateTBs { get; set; }
        public virtual DbSet<CourseAssignTB> CourseAssignTBs { get; set; }
        public virtual DbSet<CourseTB> CourseTBs { get; set; }
        public virtual DbSet<RoomNoTB> RoomNoTBs { get; set; }
        public virtual DbSet<EnrollCourseTB> EnrollCourseTBs { get; set; }
    }
}
