//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementSystemMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentTB()
        {
            this.CodeingClubTBs = new HashSet<CodeingClubTB>();
            this.NetworkingClubTBs = new HashSet<NetworkingClubTB>();
            this.EnrollCourseTBs = new HashSet<EnrollCourseTB>();
        }
    
        public int Id { get; set; }
        public int DepartmentId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string StudentName { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public string Address { get; set; }
        public string RegistrationNo { get; set; }
        public string Password { get; set; }
    
        public virtual RoleTB RoleTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CodeingClubTB> CodeingClubTBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NetworkingClubTB> NetworkingClubTBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnrollCourseTB> EnrollCourseTBs { get; set; }
    }
}
