//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementSystemMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeacherTB()
        {
            this.CodingClubAdvTBs = new HashSet<CodingClubAdvTB>();
            this.NetClubAdvTBs = new HashSet<NetClubAdvTB>();
            this.CourseAssignTBs = new HashSet<CourseAssignTB>();
        }
    
        public int Id { get; set; }
        public int DesignationId { get; set; }
        public int DepartmentId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string TeacherName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
        public double CreditToBeTaken { get; set; }
        public double ReminingCredit { get; set; }
        public string Password { get; set; }
    
        public virtual RoleTB RoleTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CodingClubAdvTB> CodingClubAdvTBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NetClubAdvTB> NetClubAdvTBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseAssignTB> CourseAssignTBs { get; set; }
    }
}
